name: Lookahead CLI

on:
  push:
    paths: ["packages/cli/**", ".github/workflows/cli.yml"]

defaults:
  run:
    working-directory: ./packages/cli

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: Install Dependencies
        run: |
          go version
          sudo wget -c https://github.com/FiloSottile/age/releases/download/v1.0.0-beta2/age-v1.0.0-beta2-linux-amd64.tar.gz -O - | sudo tar -xvz -C /usr/local
      - name: Decrypt keys
        run : |
          echo $AGE_KEY > ./internal/firebase/key.txt
          ls -lh ./internal/firebase/key.txt
          /usr/local/age/age -d -i ./internal/firebase/key.txt ./internal/firebase/keys.go.age > ./internal/firebase/keys.go
        env:
          AGE_KEY: ${{ secrets.AGE_SECRET }}
      - name: Build the CLI
        run: |
          FIXEDVER=1 make build
          find ./build