name: Lookahead CLI

on:
  push:
    paths: ["packages/cli/**", ".github/workflows/cli.yml"]

defaults:
  run:
    working-directory: ./packages/cli

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: Install Dependencies
        run: |
          go version
          go mod download
          sudo wget –quiet -c https://github.com/FiloSottile/age/releases/download/v1.0.0-beta2/age-v1.0.0-beta2-linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local
      - name: Decrypt keys
        run : |
          cd internal/firebase
          echo $AGE_KEY > key.txt
          ls -lh key.txt
          /usr/local/age/age -d -i key.txt keys.go.age > keys.go
        env:
          AGE_KEY: ${{ secrets.AGE_SECRET }}
      - name: Build the CLI
        run: |
          FIXEDVER=1 make build
          make archive
          find ./build
      - uses: actions/upload-artifact@v2
        with:
          name: look-linux-amd64
          path: ${{ github.workspace }}build/look_linux_amd64.gz
      - uses: actions/upload-artifact@v2
        with:
          name: look-darwin-amd64
          path: ${{ github.workspace }}build/look_darwin_amd64.gz
      - uses: actions/upload-artifact@v2
        with:
          name: look-win32-amd64
          path: ${{ github.workspace }}build/look_win32_amd64.zip