name: Lookahead CLI

on:
  push:
    paths: ["packages/cli/**"]

defaults:
  run:
    working-directory: ./packages/cli

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: Install Dependencies
        run: |
          go version
          sudo curl https://github.com/FiloSottile/age/releases/download/v1.0.0-beta2/age-v1.0.0-beta2-linux-amd64.tar.gz -o /usr/bin/age.tar.gz
          sudo gzip -d < /usr/bin/age.tar.gz | tar xvf -
          go get -u ./...
      - name: Decrypt keys
        run : |
          echo $AGE_KEY > ./internal/firebase/key.txt
          age -d -i ./internal/firebase/key.txt ./internal/firebase/keys.go.age > ./internal/firebase/keys.go
        env:
          AGE_KEY: ${{ secrets.AGE_SECRET }}
      - name: Build the CLI
        run: |
          FIXEDVER=1 make build
          find ./build