name: Lookahead Web App

on:
  push:
    paths: "packages/web/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/packages/web/.next/cache
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
          ${{ runner.os }}-
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: yarn install
      - name: Build the app
        run: yarn workspace @lookahead/web build
        env:
          NEXT_PUBLIC_FIREBASE_APP_CONFIG: ${{ secrets.FIREBASE_APP_CONFIG }}
      - name: Run tests
        run: yarn workspace @lookahead/web test
        env:
          FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
      - name: Deploy to Dev build
        run: yarn workspace @lookahead/web deploy:dev -m "$(git show -s --format=%s)" --token $FIREBASE_CI_TOKEN
        env:
          CI: true
          FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
