name: Lookahead Web App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install -g firebase-tools
      - run: yarn install
      - name: Build the app
        run: yarn workspace @lookahead/web build
        env:
          NEXT_PUBLIC_FIREBASE_APP_CONFIG: ${{ secrets.FIREBASE_APP_CONFIG }}
        # - run: yarn test
      - name: Deploy to Dev build
        run: yarn workspace @lookahead/web deploy:dev -m "$(git show -s --format=%s)" --token $FIREBASE_CI_TOKEN
        env:
          CI: true
          FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
