name: Lookahead Web App

on:
  push:
    paths: ["packages/web/**", ".github/workflows/web.yml"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/web
    env:
      VITE_FIREBASE_APP_CONFIG: ${{ secrets.FIREBASE_APP_CONFIG }}
      FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: yarn install --prefer-offline
      - name: Build the app (test build)
        run: yarn build:test
      - name: Run tests
        run: yarn test
      - name: Build for production
        run: yarn build
      - name: Deploy to dev build
        run: yarn deploy:dev --token $FIREBASE_CI_TOKEN
